{% set name = "repro-tarfile" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/repro_tarfile-{{ version }}.tar.gz
  sha256: e3c02847a8e28102acdb3b041a8643cc82e270bbc1cd4b00660bc038c1af2e68

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8

test:
  imports:
    - repro_tarfile
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A tiny, zero-dependency replacement for Python's tarfile standard library for creating reproducible/deterministic tar archives.
  home: https://github.com/drivendataorg/repro-tarfile
  dev_url: https://github.com/drivendataorg/repro-tarfile
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jayqi
